#!/bin/bash

clear
echo "
 __                                      ____                                               ______                ___      
/\ \       __                           /\  _`\                                            /\__  _\              /\_ \     
\ \ \     /\_\    ___   __  __  __  _   \ \,\L\_\  __  __  _ __   __  __     __   __  __   \/_/\ \/   ___     ___\//\ \    
 \ \ \  __\/\ \ /' _ `\/\ \/\ \/\ \/'\   \/_\__ \ /\ \/\ \/\`'__\/\ \/\ \  /'__`\/\ \/\ \     \ \ \  / __`\  / __`\\ \ \   
  \ \ \L\ \\ \ \/\ \/\ \ \ \_\ \/>  </     /\ \L\ \ \ \_\ \ \ \/ \ \ \_/ |/\  __/\ \ \_\ \     \ \ \/\ \L\ \/\ \L\ \\_\ \_ 
   \ \____/ \ \_\ \_\ \_\ \____//\_/\_\    \ `\____\ \____/\ \_\  \ \___/ \ \____\\/`____ \     \ \_\ \____/\ \____//\____\
    \/___/   \/_/\/_/\/_/\/___/ \//\/_/     \/_____/\/___/  \/_/   \/__/   \/____/ `/___/> \     \/_/\/___/  \/___/ \/____/
                                                                                      /\___/                               
                                                                                      \/__/                                
"

read -p 'How many hosts do you want to scan?: ' input

counter=0

while [ $counter -lt $input ]
do
((counter++))
read -p 'Enter host IP address: ' host$counter
set "host$counter=$host1"
echo "1. $host1"
if [ -n "${host2+set}" ];then
set "host"$counter="$host2"
echo "2. $host2"
fi
if [ -n "${host3+set}" ];then
set "host"$counter="$host3"
echo "3. $host3"
fi
if [ -n "${host4+set}" ];then
set "host"$counter="$host4"
echo "4. $host4"
fi
if [ -n "${host5+set}" ];then
set "host"$counter="$host5"
echo "5. $host5"
fi
if [ -n "${host6+set}" ];then
set "host"$counter="$host6"
echo "6. $host6"
fi
if [ -n "${host7+set}" ];then
set "host"$counter="$host7"
echo "7. $host7"
fi
if [ -n "${host8+set}" ];then
set "host"$counter="$host8"
echo "8. $host8"
fi
if [[ "$number" == "$input" ]]; then
break
fi
done
read -p "Are you sure? [y/n]" -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

clear

read -sp 'Remote host root Password: ' password

echo $password > /home/assessor/Documents/nothing
####################################################################################################
if [ -n "${host1+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" ssh -q root@"$host1" <<EOF
mkdir /etc/$host1
ps -aef > /etc/$host1/proc
netstat -t > /etc/$host1/netstat
lsmod > /etc/$host1/drivers
cd /
find **/ >> /etc/$host1/dir
exit
EOF

echo "Finished creating Files for $host1"

fi

if [ -n "${host1+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" sftp -q root@"$host1" <<EOF
get -rf /etc/$host1 /home/assessor/Desktop
rm /etc/$host1/*
rmdir /etc/$host1
exit
EOF

echo "Finished moving and deleting Files for $host1"

fi
##################################################################################################
if [ -n "${host2+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" ssh -q root@"$host2" <<EOF
mkdir /etc/$host2
ps -aef > /etc/$host2/proc
netstat -t > /etc/$host2/netstat
lsmod > /etc/$host2/drivers
cd /
find **/ >> /etc/$host2/dir
exit
EOF

echo "Finished creating Files for $host2"

fi
if [ -n "${host2+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" sftp -q root@"$host2" <<EOF
get -rf /etc/$host2 /home/assessor/Desktop
rm /etc/$host2/*
rmdir /etc/$host2
exit
EOF

echo "Finished moving and deleting Files for $host2"

fi
##################################################################################################
if [ -n "${host3+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" ssh -q root@"$host3" <<EOF
mkdir /etc/$host3
ps -aef > /etc/$host3/proc
netstat -t > /etc/$host3/netstat
lsmod > /etc/$host3/drivers
cd /
find **/ >> /etc/$host3/dir
exit
EOF

echo "Finished creating Files for $host3"

fi
if [ -n "${host3+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" sftp -q root@"$host3" <<EOF
get -rf /etc/$host3 /home/assessor/Desktop
rm /etc/$host3/*
rmdir /etc/$host3
exit
EOF

echo "Finished moving and deleting Files for $host3"

fi
##################################################################################################
if [ -n "${host4+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" ssh -q root@"$host4" <<EOF
mkdir /etc/$host4
ps -aef > /etc/$host4/proc
netstat -t > /etc/$host4/netstat
lsmod > /etc/$host4/drivers
cd /
find **/ >> /etc/$host4/dir
exit
EOF

echo "Finished creating Files for $host4"

fi
if [ -n "${host4+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" sftp -q root@"$host4" <<EOF
get -rf /etc/$host4 /home/assessor/Desktop
rm /etc/$host4/*
rmdir /etc/$host4
exit
EOF

echo "Finished moving and deleting Files for $host4"

fi
##################################################################################################
if [ -n "${host5+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" ssh -q root@"$host5" <<EOF
mkdir /etc/$host5
ps -aef > /etc/$host5/proc
netstat -t > /etc/$host5/netstat
lsmod > /etc/$host5/drivers
cd /
find **/ >> /etc/$host5/dir
exit
EOF

echo "Finished creating Files for $host5"

fi
if [ -n "${host5+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" sftp -q root@"$host5" <<EOF
get -rf /etc/$host5 /home/assessor/Desktop
rm /etc/$host5/*
rmdir /etc/$host5
exit
EOF

echo "Finished moving and deleting Files for $host5"

fi
#################################################################################################
if [ -n "${host6+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" ssh -q root@"$host6" <<EOF
mkdir /etc/$host6
ps -aef > /etc/$host6/proc
netstat -t > /etc/$host6/netstat
lsmod > /etc/$host6/drivers
cd /
find **/ >> /etc/$host6/dir
exit
EOF

echo "Finished creating Files for $host6"

fi
if [ -n "${host6+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" sftp -q root@"$host6" <<EOF
get -rf /etc/$host6 /home/assessor/Desktop
rm /etc/$host6/*
rmdir /etc/$host6
exit
EOF

echo "Finished moving and deleting Files for $host6"

fi
#################################################################################################
if [ -n "${host7+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" ssh -q root@"$host7" <<EOF
mkdir /etc/$host7
ps -aef > /etc/$host7/proc
netstat -t > /etc/$host7/netstat
lsmod > /etc/$host7/drivers
cd /
find **/ >> /etc/$host7/dir
exit
EOF

echo "Finished creating Files for $host7"

fi
if [ -n "${host7+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" sftp -q root@"$host7" <<EOF
get -rf /etc/$host7 /home/assessor/Desktop
rm /etc/$host7/*
rmdir /etc/$host7
exit
EOF

echo "Finished moving and deleting Files for $host7"

fi
################################################################################################
if [ -n "${host8+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" ssh -q root@"$host8" <<EOF
mkdir /etc/$host8
ps -aef > /etc/$host8/proc
netstat -t > /etc/$host8/netstat
lsmod > /etc/$host8/drivers
cd /
find **/ >> /etc/$host8/dir
exit
EOF

echo "Finished creating Files for $host8"

fi
if [ -n "${host8+set}" ]; then
sshpass -f "/home/assessor/Documents/nothing" sftp -q root@"$host8" <<EOF
get -rf /etc/$host8 /home/assessor/Desktop
rm /etc/$host8/*
rmdir /etc/$host8
exit
EOF

echo "Finished moving and deleting Files for $host8"

fi
################################################################################################
rm /home/assessor/Documents/nothing

echo All done!
